### PR TITLE
Separate App Service slot deploy and slot swap steps

### PR DESCRIPTION
**Pull request by lestermarch**
- Splits the existing `azure_web_app_slot_swap_deploy.yml` into two steps to allow for approval gates between slot swaps.

### CODE REVIEW

**Review by andylangridge — COMMENTED** [review]
Since the slot deploy step is basically a copy of the deploy step, perhaps a cleaner way would be to just add a slot parameter to the existing deploy step? Maybe with a default value of an empty string. Then you could add a tiny bit of logic in the script to check if you're deploying to a slot or not.

Also, I think the combined step can be removed? As it's a bit redundant without the ability to wait and do smoke tests considering the Continuous Deployment feature apparently sorts out the downtime issue.

**Comment by lestermarch** [comment]
> Since the slot deploy step is basically a copy of the deploy step, perhaps a cleaner way would be to just add a slot parameter to the existing deploy step? Maybe with a default value of an empty string. Then you could add a tiny bit of logic in the script to check if you're deploying to a slot or not.

In effect it does replace the `azure_web_app_deploy` step. I could set the default slot to `producton` which would mean by default the container is deployed to the production slot just as `azure_web_app_deploy` does currently. We would then specify `appStagingSlotName: staging` for deployments to the staging (or other named) slot. If you're content with that notion then I can also remove `azure_web_app_deploy.yml` in this release @andylangridge?

**Comment by lestermarch** [comment]
> Also, I think the combined step can be removed? As it's a bit redundant without the ability to wait and do smoke tests considering the Continuous Deployment feature apparently sorts out the downtime issue.

Removed in [a03ef58](https://github.com/Planning-Inspectorate/common-pipeline-templates/pull/53/commits/a03ef586bada9fa66f25d240ce9720398d496448)

**Comment by andylangridge** [comment]
> > Since the slot deploy step is basically a copy of the deploy step, perhaps a cleaner way would be to just add a slot parameter to the existing deploy step? Maybe with a default value of an empty string. Then you could add a tiny bit of logic in the script to check if you're deploying to a slot or not.
> 
> In effect it does replace the `azure_web_app_deploy` step. I could set the default slot to `producton` which would mean by default the container is deployed to the production slot just as `azure_web_app_deploy` does currently. We would then specify `appStagingSlotName: staging` for deployments to the staging (or other named) slot. If you're content with that notion then I can also remove `azure_web_app_deploy.yml` in this release @andylangridge?

Sorry to be pedantic! But in terms of naming I'd rather keep `azure_web_app_deploy.yml`, and have the only reference to Slot be in the parameter. Basically, from a developer writing a pipeline point of view, I think a step to deploy to a web app makes more sense, with the option to choose a slot if needed. Calling the whole step "Deploy Container to Azure Web App Slot" seems confusing to me!

**Comment by lestermarch** [comment]
> Sorry to be pedantic! But in terms of naming I'd rather keep `azure_web_app_deploy.yml`, and have the only reference to Slot be in the parameter.

Makes sense! Updated in [8bafb9f](https://github.com/Planning-Inspectorate/common-pipeline-templates/pull/53/commits/8bafb9f291f963c5b56cc7a6696f9606d5e5de88)

- The deploy step now defaults to the `production` slot for cases where staging slot deployments are undesirable. 
- The slot swap step now defaults to a staging slot of `production` and target slot of `production` with a check to only swap slots if the staging slot and production slot names are different (e.g. `staging` and `production`). This is to avoid situations where the prior step (deploy) deploys direct to the `production` slot, as then the swap from `staging` to `production` should not occur otherwise it would swap out the freshly deployed container.

**Review by andylangridge — APPROVED** [review]

**Pull request merged**
